[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
memchr = { version = "*", path = "../memchr"}
search = { version = "*", path = "../search" }
